### ISSUE TITLE
Ampersand ( & ) can't be used in model

### ISSUE THREAD

**Issue by mrtankjump** [Color-Of-Code/dokuwiki-plugin-bpmnio#1]
Title.

**Comment by jdehaan** [comment]
Can you please give an example? Did you think of using XML entities? [I mean you should use `&amp;` instead of a single `&` inside the XML model]

**Comment by mrtankjump** [comment]
The bpmn.io editor exports as `&#38;` but `&amp;` doesn't work either. I tested a few other XML entities, both < `&#60;`  and > `&#62;` work fine, but double quotes `&#34;` break it. The entire model fails to write. See below for rendered HTML when using the below XML.

``` html
<div>
   <div class="canvas">
      <div class="bjs-container" style="width: 100%; height: 100%; position: relative;">
         <a href="http://bpmn.io" target="_blank" class="bjs-powered-by" title="Powered by bpmn.io" style="position: absolute; bottom: 15px; right: 15px; z-index: 100">
            <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADQAAAA0CAMAAADypuvZAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAADBQTFRFiMte9PrwldFwfcZPqtqN0+zEyOe1XLgjvuKncsJAZ70y6fXh3vDT////UrQV////G2zN+AAAABB0Uk5T////////////////////AOAjXRkAAAHDSURBVHjavJZJkoUgDEBJmAX8979tM8u3E6x20VlYJfFFMoL4vBDxATxZcakIOJTWSmxvKWVIkJ8jHvlRv1F2LFrVISCZI+tCtQx+XfewgVTfyY3plPiQEAzI3zWy+kR6NBhFBYeBuscJLOUuA2WVLpCjVIaFzrNQZArxAZKUQm6gsj37L9Cb7dnIBUKxENaaMJQqMpDXvSL+ktxdGRm2IsKgJGGPg7atwUG5CcFUEuSv+CwQqizTrvDTNXdMU2bMiDWZd8d7QIySWVRsb2vBBioxOFt4OinPBapL+neAb5KL5IJ8szOza2/DYoipUCx+CjO0Bpsv0V6mktNZ+k8rlABlWG0FrOpKYVo8DT3dBeLEjUBAj7moDogVii7nSS9QzZnFcOVBp1g2PyBQ3Vr5aIapN91VJy33HTJLC1iX2FY6F8gRdaAeIEfVONgtFCzZTmoLEdOjBDfsIOA6128gw3eu1shAajdZNAORxuQDJN5A5PbEG6gNIu24QJD5iNyRMZIr6bsHbCtCU/OaOaSvgkUyDMdDa1BXGf5HJ1To+/Ym6mCKT02Y+/Sa126ZKyd3jxhzpc1r8zVL6YM1Qy/kR4ABAFJ6iQUnivhAAAAAAElFTkSuQmCC">
         </a>
      </div>
   </div>
 </div>
```

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn">
  <bpmn:process id="Process_1" isExecutable="false">
    <bpmn:task id="Task_00eryk4" name="Design &#38; Draw" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1">
      <bpmndi:BPMNShape id="Task_00eryk4_di" bpmnElement="Task_00eryk4">
        <dc:Bounds x="5" y="5" width="100" height="80" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

**Comment by jdehaan** [comment]
Thanks a lot for the example. I see the problem clearly now... This is annoying, I now pretty well understood the symptoms but currently I've no clue where the info gets lost. Sorry for slow reaction time (due to private reasons last days).

> `&#38;#38;`

Makes it "work" so actually something is translating already the XML entities too early inside script.js `var xml = jQuery(tag).text();` is likely doing too much. I've to look at it more closely and find a solution...

**Comment by jdehaan** [comment]
Using `.html()` instead of `.text()` did not help. I have to figure out a better (non destructive) way to store and extract the xml string to be handed out the the bpmnio library...

**Comment by jdehaan** [comment]
I believe I have now solved the issue. Can please also confirm with the latest state of master branch that the issue is solved?

**Comment by mrtankjump** [comment]
Issue is solved as far as I've tested it. Thank you for the rapid response.

**Comment by jdehaan** [comment]
Thank you too for your report thus contributing to making the plug-in better!
