### ISSUE TITLE
error: startSectionEdit: $data "plugin_bpmnio" is NOT an array! One of your plugins needs an update.

### ISSUE THREAD

**Issue by stefanobasta** [Color-Of-Code/dokuwiki-plugin-bpmnio#14]
Since the new upgrade of Dokuwiki an error pops up.

**Comment by rattkin** [comment]
+1
The drawing is still visible, it works despite the error.

**Comment by jdehaan** [comment]
I could reproduce the bug on my system.

See also hints in:

- https://github.com/splitbrain/dokuwiki/issues/2326
- example of fix for another plugin: https://github.com/dokufreaks/plugin-include/pull/224
