### ISSUE TITLE
Strange visualisation for DokuWiki Version Igor

### ISSUE THREAD

**Issue by update-freak** [Color-Of-Code/dokuwiki-plugin-bpmnio#19]
Hello
after updating to version rc2022-06-26 "Igor" RC2 I noticed that the visualisation is strange (see testprocess).
I downloaded the version with MicroApache for testing (old and new version (RC) of DokuWiki).
Please fix this problem with the new DokuWiki release
![testbild](https://user-images.githubusercontent.com/40196995/179360524-462c0781-eab8-4c58-904d-9b984ba045e5.png)

**Comment by jdehaan** [comment]
Thanks for the report, I will have a look into it upcoming week.

**Comment by jdehaan** [comment]
I upgraded the bpmn-js module as a pre-requisite step, as anyways the precedently used version is quite out of date. The newer bpmn-js features a promise based API and has a slightly different layer and bounding box API. I adapted the code but for today I have to give up further steps regarding checking the behavior on newer dokuwiki versions, I adapted on Greebo. Checks for Hogfather and Igor are pending.

**Comment by jdehaan** [comment]
I went through Greebo, Hogfather and finally Igor, the new version looks like working to me. Can you give it a try by upgrading to the latest version @update-freak ?

**Comment by update-freak** [comment]
thanks for going through the different versions. I checked the Release Candidate (default selection when you try to download Dokuwiki) with included Web-Server.  When I try to insert a process a got this appearance:

![2022-07-20](https://user-images.githubusercontent.com/40196995/180037909-4aebcb09-5dde-44f9-b680-00b4e0a607ff.png)

**Comment by jdehaan** [comment]
Could you please tell me which browser and which version you are using? I will try to reproduce that. I took the bare tarnall of dokuwiki with the plug-in in a php docker container so I think from the server perspective it is quite pristine. I suspect some client/ browser side issue.

**Comment by update-freak** [comment]
sure. I used
- Chrome 103.0.5060.134 with extensions: Bitwarden, ClearURLs, I don't care about cookies, Join, Privacy Badger, uBlock Origin
- Microsoft Edge 103.0.1264.62 without extensions
and deactivated network add blocker AdGuard Home
- For DokuWiki there is the information: Apache 2.4.46, PHP 7.4.12, GD2 and SQLite
- All processes are created with Camunda Modeler V5.1.0.

An example is this one
`<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_0i94x1k" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.1.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.0.0">
  <bpmn:process id="Process_17rvo4j" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_1rfi7by</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:task id="Activity_1t3fe26" name="Beispiel Aufgabe 1">
      <bpmn:incoming>Flow_1rfi7by</bpmn:incoming>
      <bpmn:outgoing>Flow_1rt5gpq</bpmn:outgoing>
    </bpmn:task>
    <bpmn:sequenceFlow id="Flow_1rfi7by" sourceRef="StartEvent_1" targetRef="Activity_1t3fe26" />
    <bpmn:task id="Activity_1t98icz" name="Beispielaufgabe 2">
      <bpmn:incoming>Flow_1rt5gpq</bpmn:incoming>
      <bpmn:outgoing>Flow_1s1h2t2</bpmn:outgoing>
    </bpmn:task>
    <bpmn:sequenceFlow id="Flow_1rt5gpq" sourceRef="Activity_1t3fe26" targetRef="Activity_1t98icz" />
    <bpmn:endEvent id="Event_0uhql6m">
      <bpmn:incoming>Flow_1s1h2t2</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_1s1h2t2" sourceRef="Activity_1t98icz" targetRef="Event_0uhql6m" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_17rvo4j">
      <bpmndi:BPMNEdge id="Flow_1rfi7by_di" bpmnElement="Flow_1rfi7by">
        <di:waypoint x="215" y="117" />
        <di:waypoint x="240" y="117" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1rt5gpq_di" bpmnElement="Flow_1rt5gpq">
        <di:waypoint x="340" y="117" />
        <di:waypoint x="390" y="117" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1s1h2t2_di" bpmnElement="Flow_1s1h2t2">
        <di:waypoint x="490" y="117" />
        <di:waypoint x="532" y="117" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="99" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1t3fe26_di" bpmnElement="Activity_1t3fe26">
        <dc:Bounds x="240" y="77" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_1t98icz_di" bpmnElement="Activity_1t98icz">
        <dc:Bounds x="390" y="77" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0uhql6m_di" bpmnElement="Event_0uhql6m">
        <dc:Bounds x="532" y="99" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
`

**Comment by jdehaan** [comment]
Thanks for the details!

I have now:
![image](https://user-images.githubusercontent.com/261428/180080073-8a25dc3b-7bc9-4b1d-b2ff-b2f0d87c8852.png)

Installed extensions
![image](https://user-images.githubusercontent.com/261428/180080497-4ef33010-1307-4bfb-bd7a-2cf501e60696.png)

Used your xml surrounding it with

```
<bpmnio zoom=1.0>
  ... your xml here
</bpmnio>

Test Beispiel 1
```

And get as a result:

![image](https://user-images.githubusercontent.com/261428/180080753-41941179-bcaf-4b67-87e6-79f011e7b239.png)


Which looks ok to me...

**Comment by jdehaan** [comment]
Ahhhhh
I finally got it reproduced after deleting all the cache folders...

![image](https://user-images.githubusercontent.com/261428/180083442-9c25eb98-6e67-4efa-9762-7d4a626c1b8e.png)


Working on it. (This makes me believe the tests I performed were bogus :-/ due to the cached files, hmmm)

**Comment by jdehaan** [comment]
I think for sure this has to do with the deferred loading of the js assets

**Comment by jdehaan** [comment]
I think I could find a part of the problem, the dokuwiki svg style: https://github.com/splitbrain/dokuwiki/issues/3690

**Comment by jdehaan** [comment]
Thanks to the hint regarding the proper use of css (🤦🏻‍♂️ ) I could manage to bring in a first working version for Igor. Thanks a bunch for your patience. I hope I got it now, could you please give it another try?

**Comment by update-freak** [comment]
Thank you very much!!
I can confirm that it works (rendering is good)

One thing i found is that for large processes or small screens (see screenshot) the process is not fully displayed and there is no possibility to scroll to the rest of the process. It would be great if you could add that function. I think with the old version this was also possible.

![Screenshot_20220721-165829_Chrome](https://user-images.githubusercontent.com/40196995/180246861-59e8308b-f426-46c3-95cd-35ff8e213e71.jpg)

**Comment by jdehaan** [comment]
True I will do that within the next days... Sorry to have broken that feature, I reworked the plugin fully after having read the documentation on how it should be.... Another thing is that the old version also had some kind of overlay to show what is "selected" on the diagram. It looks like the newer bpmnjs version handles that differently. I have started also reading about this, but this week I am running out of free time for that I fear.

**Comment by jdehaan** [comment]
@update-freak I could arrange to get a state where the bpmn is rendered using 100% of the space available and if it is bigger then display a scrollbar. I think this is nice to have the BPMN.iO Logo aligned to the right instead of a messier look.

If you are ok with the results now, feel free to close the ticket.

**Comment by update-freak** [comment]
Yes, I can confirm that the scrollbar is working as exspected. Now I'm very happy with the result :)
Thank you for your effort and the quick solution!!
