### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by rattkin** [Color-Of-Code/dokuwiki-plugin-bpmnio#2]
From left to right:
xml file, bpmn.io editor, rendered output in dokuwiki

![image](https://cloud.githubusercontent.com/assets/910080/15331647/915b2af0-1c62-11e6-92e3-08ef33099a58.png)

in the dokuwiki render, there is a problem with character encoding.

**Comment by jdehaan** [comment]
Thanks for the report! Fortunately I could solve the issue quickly. I provided an update please double check if it works for you too.

**Comment by rattkin** [comment]
Great, that's fixed.
Thank You, super job.

**Comment by jdehaan** [comment]
Thank you for the reporting the issue and thus contributing to the improvement of the plugin!
It's a quite fresh release so there might be more annoying things lurking....
