### ISSUE TITLE
unable to edit section

### ISSUE THREAD

**Issue by rattkin** [Color-Of-Code/dokuwiki-plugin-bpmnio#3]
When the bpmnio image is at the bottom of the section, i am unable to edit the section.

The edit button is visible, but can not be clicked:

![image](https://cloud.githubusercontent.com/assets/910080/15394320/923357e2-1dd2-11e6-8605-569b2c760a41.png)

culprit:
div class="bjs-container"

**Comment by jdehaan** [comment]
I understood the issue and agree that it has to be fixed. I am sorry but probably I will not be able to do this very timely (I am totally overloaded). I do my best to solve it soon - latest until end of next week.

**Comment by jdehaan** [comment]
It's for sure not the most elegant solution but:
- workaround with `\\` to introduce space after each diagram is not looking good
- changing the .secedit class style works but introduces unwanted effects elsewhere
- Removing or changing the logo is not allowed by the license (maybe an option by contacting the authors to have them introduce some pixels so the logo does not get to the uttermost bottom right corner?)

So I went by introducing a right margin. Do you have a better idea?
