### ISSUE TITLE
how do we link models?

### ISSUE THREAD

**Issue by alibama** [Color-Of-Code/dokuwiki-plugin-bpmnio#44]
sorry if this is just stupid... 

https://lexipedia.xyz/doku.php?id=reg_cf_exemptions

i'm using this plugin to start building an encyclopedia of legally reviewed business process & would like to start linking sub processes properly?  not sure how this works in the dokuwiki ecosystem?  thoughts appreciated?

also might be useful to have a list going of active sites using this module?  just a thought = thank you so much for putting this together, it's a great tool and the main reason we've decided to launch with dokuwiki :)

**Comment by jdehaan** [comment]
I integrated bpmnio and do not know much about how exactly the diagram linking within bpmnio is designed to work.

What I would do if I were in your situation is split the sub processes into separate smaller diagrams and place these inside different sections on the wiki page, or even if that makes sense on different wiki pages. That makes things better to view anyways: Provide an overall diagram without the details and macro blocks for the sub processes and then linking to the sections with more details from a bullet point list below the overview diagram.

You have to think about the maintenance of all this in case you switch tools or have to adapt to some newer version. By doing so you won't depend so strongly upon this plugin/bpmnio and could add maybe if appropriate other types of diagrams in form of pictures....

I was planning to look into how to introduce linking inside the diagram as you're not the first one to ask. But this is rather complicated and not easy to realize properly (link to things that are inside a wiki instance are usually dynamically created inside the backend in php. But... bpmnio runs inside the browser and there is no easy mean to resolve things and requires to add infrastructure for assisting during edits. Just to explain in a few works why a seemingly easy feature is actually technically difficult to realize in this case)

I hope the workaround is actionable for you. Actually it would be IMHO even a more durable solution while probably not being what you initially expected. Does that make sense to you?

**Comment by alibama** [comment]
this totally makes sense... i guess i just need to get a little more familiar with the bpmnio models and then plan to link to other pages.... 

that's absolutely the right way to go for layout and probably for reusability too....

if you have any other insights feel free to reach out & thank you again for your work!
